trigger: 
- main

pool: 
 name: todoapp

stages:
  - stage:  terraforminstall
    displayName: terraform install
    jobs:
    - job: terraforminstall
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'

  - stage: terraformdeploy
    dependsOn: terraforminstall
    jobs:
    - job: terraforminit1
      displayName: terraforminit
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: 'C:\Users\HP\Downloads\agent\vsts-agent-win-x64-4.274.1\_work\1\s\Environment\dev'
          backendServiceArm: 'todoapp'
          backendAzureRmStorageAccountName: 'todoapprg'
          backendAzureRmContainerName: 'todoappcontainer'
          backendAzureRmKey: 'terraform.tfstate'

    - job: terraformvalidate
      displayName: terraform validate
      dependsOn: terraforminit1
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: 'C:\Users\HP\Downloads\agent\vsts-agent-win-x64-4.274.1\_work\1\s'

    - job: terraformplan
      displayName: terraformplan
      dependsOn: terraformvalidate
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: 'C:\Users\HP\Downloads\agent\vsts-agent-win-x64-4.274.1\_work\1\s\Environment\dev'
          environmentServiceNameAzureRM: 'todoapp'

  - stage: scanning
    displayName: scanning
    jobs:
    - job: tfsecscanning
      steps:
      - task: tfsec@1
        inputs:
          version: 'v1.26.0'
          dir: 'C:\Users\HP\Downloads\agent\vsts-agent-win-x64-4.274.1\_work'

    - job: trivvyscanning
      steps:
      - task: trivy@2
        inputs:
          version: 'latest'
          type: 'repository'
          target: 'C:\Users\HP\Downloads\agent\vsts-agent-win-x64-4.274.1\_work'
          scanners: 'license, misconfig, secret, vuln'
          severities: 'UNKNOWN, LOW, MEDIUM, HIGH, CRITICAL'
          ignoreScanErrors: true
          failOnSeverityThreshold: 'LOW'
          publish: true

  - stage: manualvalidation
    jobs:
    - job: manualvalidation
      pool: server
      steps:
      - task: ManualValidation@1
        inputs:
          notifyUsers: 'vipulsingh463@gmail.com'
          approvers: 'vipulsingh463@gmail.com'
          instructions: 'fhg'
          onTimeout: 'resume'

  - stage: terraformapply
    dependsOn: manualvalidation
    jobs:
    - job: terraforminit
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: 'C:\Users\HP\Downloads\agent\vsts-agent-win-x64-4.274.1\_work\1\s\Environment\dev'
          backendServiceArm: 'todoapp'
          backendAzureRmStorageAccountName: 'todoapprg'
          backendAzureRmContainerName: 'todoappcontainer'
          backendAzureRmKey: 'terraform.ftstate'

    - job: terraformapply
      dependsOn: terraforminit
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: 'C:\Users\HP\Downloads\agent\vsts-agent-win-x64-4.274.1\_work\1\s\Environment\dev'
          environmentServiceNameAzureRM: 'todoapp'
      

